/**
 * Design Specs list page — Server Component.
 *
 * Shows a simple redirect to pipelines for now, since specs are accessed
 * via pipeline detail → "View Spec" link.
 */

import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function DesignSpecsPage() {
  return (
    <main className="mx-auto max-w-5xl p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight">Design Specs</h1>
        <p className="text-sm text-muted-foreground">
          Design specs are generated by pipelines. View a pipeline to see its
          spec.
        </p>
      </div>
      <Link href="/pipelines">
        <Button variant="outline">Go to Pipelines</Button>
      </Link>
    </main>
  );
}
